def jrPrintHelp():
    print("\n")
    print("*************************************************************************************************************")
    print("*** AYUDA ***************************************************************************************************")
    print("*************************************************************************************************************")
    print("jrPDFMerge, es un proceso que fusiona el contenido de varios ficheros PDF en un sólo fichero PDF.\n")
    print("Usted puede pasarle hasta 3 parametros, con la siguiente forma y orden:")
    print("jrPDFMerge NombreAgrupado CarpetaOrigen CarpetaDestino \n")
    print("\tNombreAgrupado = Nombre que se le dará al fichero final (resultado de la agrupar a todos los pdf.)")
    print("\tCarpetaOrigen  = Ubicación de los ficheros pdf que desea fusionar.")
    print("\tCarpetaOrigen  = Ubicación dónde el proceso dejará el fichero pdf resultado de la fusión.")
    print("\nNota Importante: \n")
    print("Debe pasar los parametros en este orden, puede pasar sólo el nombre, si quiere y este, debe ser válido.")
    print("*************************************************************************************************************")
    print("Ejemplo de llamadas:\n")
    print("(py37) D:\>python jrmergepdf.py -?")
    print("(py37) D:\>python jrmergepdf.py TotalPDF d:\Cursos\python\IN d:\Cursos\python\OUT")
    print("*************************************************************************************************************")
    